### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by bf-ckiendl** [florath/rmtoo#21]
The installation instructions don't seem to work. I've had multiple attempts and I have yet to get it to work even partially.

Currently, it looks like I may have installed it, but when I run "make" as per the instructions, it tells me the file .rmtoo_dependencies was not found.

Is there a binary installer or a non-vendor-specific VM image that I could use?

**Comment by florath** [comment]
Can you please try the virtualenv version - if you not already did?

Can you please copy&paste the error message here?

**Comment by bf-ckiendl** [comment]
I am trying the virtualenv version and have had multiple different error messages on different attempts.
I've also tried both Python 2 and 3 (currently 2.7.3).
I am currently trying the installation instructions at https://github.com/florath/rmtoo#installation-using-virtualenv-pip
I'm at "Usage" trying "make" on the copied template project and, well...

> Makefile:32: .rmtoo_dependencies: Datei oder Verzeichnis nicht gefunden
> rmtoo -j file://Config.json \
>                 --create-makefile-dependencies=.rmtoo_dependencies
> Traceback (most recent call last):
>   File "/root/RMTOO/venv/bin/rmtoo", line 11, in <module>
>     sys.exit(main())
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 89, in main
>     main_impl(sys.argv[1:], sys.stdout, sys.stderr)
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 81, in main_impl
>     exitfun(not mainfunc(args, mstdout, mstderr))
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/RmtooMain.py", line 72, in main_func
>     config, input_mods = MainHelper.main_setup(args, mstdout, mstderr)
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 37, in main_setup
>     config = MainHelper.main_setup_config(args)
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/main/MainHelper.py", line 30, in main_setup_config
>     config.merge_cmd_line_params(args)
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/Cfg.py", line 170, in merge_cmd_line_params
>     ldicts = CmdLineParams.create_dicts(args)
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 123, in create_dicts
>     lresult.append(CmdLineParams.add_args(args))
>   File "/root/RMTOO/venv/local/lib/python2.7/site-packages/rmtoo/lib/configuration/CmdLineParams.py", line 109, in add_args
>     if args is None or args == []:
>   File "/usr/lib/python2.7/argparse.py", line 1158, in __eq__
>     return vars(self) == vars(other)
> TypeError: vars() argument must have __dict__ attribute
> make: *** [.rmtoo_dependencies] Fehler 1

When I `touch .rmtoo_dependencies`, it changes to 
> (cd artifacts && \
>            gnuplot /root/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>            epstopdf stats_reqs_cnt.eps)
> /bin/sh: 2: gnuplot: not found
> make: *** [artifacts/requirements.pdf] Fehler 127

After `aptitude install gnuplot`, it's 
> (cd artifacts && \
>            gnuplot /root/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>            epstopdf stats_reqs_cnt.eps)
> "/root/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc", line 8: warning: Skipping unreadable file "stats_reqs_cnt.csv"
> "/root/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc", line 8: No data in plot
> 
> make: *** [artifacts/requirements.pdf] Fehler 1

It's been going like that for days. No matter what I do to fix an error, another error pops up.
Everything I read about rmtoo looks promising, otherwise I wouldn't keep trying, but this thing _really_ needs a comprehensive installer.

I'll try again on a different distro later today.


(And for the record: No, I'm not permanently running as root.)

**Comment by bf-ckiendl** [comment]
Completely different machine, different distro, etc.
Same initial issue:
> Makefile:32: .rmtoo_dependencies: Datei oder Verzeichnis nicht gefunden
> rmtoo -j file://Config.json \
>         --create-makefile-dependencies=.rmtoo_dependencies
> rmtoo -j file://Config.json
> +++ Error:Analytics:TopicCohe:WhatsAbout:result is '-10'
> +++ Error:Analytics:TopicCohe:WhatsAbout:WhatsAbout: Topic coherence inadequate: inner 0 / outer 0
> +++ WARN: gradient is positive [0]: you get more than you finished
> +++ WARN: gradient is positive [0]: you get more than you finished
> +++ WARN: gradient is positive [0]: you get more than you finished
> +++ WARN: gradient is positive [0]: you get more than you finished
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>    epstopdf stats_reqs_cnt.eps)
> /bin/sh: 2: gnuplot: not found
> Makefile:51: die Regel für Ziel „artifacts/requirements.pdf“ scheiterte
> make: *** [artifacts/requirements.pdf] Fehler 127

Same remedies as before, this time leading to
> $ make
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>    epstopdf stats_reqs_cnt.eps)
> Warning: empty x range [1.53746e+09:1.53746e+09], adjusting to [1.52208e+09:1.55283e+09]
> Warning: empty y range [2:2], adjusting to [1.98:2.02]
> /bin/sh: 3: epstopdf: not found
> Makefile:51: die Regel für Ziel „artifacts/requirements.pdf“ scheiterte
> make: *** [artifacts/requirements.pdf] Fehler 127

Soooo `aptitude install texlive-font-utils` (which provides epstopdf).
> $ make
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>    epstopdf stats_reqs_cnt.eps)
> Warning: empty x range [1.53746e+09:1.53746e+09], adjusting to [1.52208e+09:1.55283e+09]
> Warning: empty y range [2:2], adjusting to [1.98:2.02]
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_burndown.inc && \
>    epstopdf stats_burndown.eps)
> "/home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_burndown.inc", line 8: warning: Skipping data file with no valid points
> Warning: empty y range [0:0], adjusting to [-1:1]
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_sprint_burndown.inc && \
>    epstopdf stats_sprint_burndown.eps)
> "/home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_sprint_burndown.inc", line 8: warning: Skipping data file with no valid points
> Warning: empty y range [0:0], adjusting to [-1:1]
> (cd artifacts && pdflatex ../latex/requirements.tex; \
>         pdflatex ../latex/requirements.tex; \
>         pdflatex ../latex/requirements.tex)
> /bin/sh: 1: pdflatex: not found
> /bin/sh: 2: pdflatex: not found
> /bin/sh: 3: pdflatex: not found
> Makefile:51: die Regel für Ziel „artifacts/requirements.pdf“ scheiterte
> make: *** [artifacts/requirements.pdf] Fehler 127

`aptitude install texlive-latex-base` (provides pdflatex)

> $ make
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_reqs_cnt.inc && \
>    epstopdf stats_reqs_cnt.eps)
> Warning: empty x range [1.53746e+09:1.53746e+09], adjusting to [1.52208e+09:1.55283e+09]
> Warning: empty y range [2:2], adjusting to [1.98:2.02]
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_burndown.inc && \
>    epstopdf stats_burndown.eps)
> "/home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_burndown.inc", line 8: warning: Skipping data file with no valid points
> Warning: empty y range [0:0], adjusting to [-1:1]
> (cd artifacts && \
>    gnuplot /home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_sprint_burndown.inc && \
>    epstopdf stats_sprint_burndown.eps)
> "/home/administrator/RMTOO/store_insight/../venv/rmtoo/contrib/gnuplot_stats_sprint_burndown.inc", line 8: warning: Skipping data file with no valid points
> Warning: empty y range [0:0], adjusting to [-1:1]
> (cd artifacts && pdflatex ../latex/requirements.tex; \
>         pdflatex ../latex/requirements.tex; \
>         pdflatex ../latex/requirements.tex)
> This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> (../latex/requirements.tex
> LaTeX2e <2017-04-15>
> Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
> (/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
> Document Class: report 2014/09/29 v1.4h Standard LaTeX document class
> (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
> (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
> (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/graphics-def/pdftex.def)))
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
> (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
> (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty)
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
> (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/backref.sty
> (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
> (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def)
> (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty)
> 
> ! LaTeX Error: File `tocloft.sty' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: sty)
> 
> Enter file name: foo_test.xxx
> 
> ! LaTeX Error: File `foo_test.xxx' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: xxx)
> 
> Enter file name: 
> 
> ! LaTeX Error: Unknown option `titles' for package `tocloft'.
> 
> See the LaTeX manual or LaTeX Companion for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.19 \usepackage
>                 {fancyhdr}
> ? 
> 

Now I'm apparently stuck in some LaTeX shell.

**Comment by florath** [comment]
What I see from your logs is, that you still miss dependencies. (A *latex-extra package?)

Currently there is no extensive documentation about the required packages: the problem is, that every distro uses its own names and places different tool in different places. (And pip cannot help here.) Also the needed tools rely on what you want to do: so you need LaTeX only in case that you want to create a PDF documentation.

A package dependency list for Debian exists:
https://github.com/florath/rmtoo/blob/master/contrib/vmsetup/dib-elements/rmtoo-small/package-installs.yaml
This is somewhat longer than needed for a already installed system - but it is known to work.

rmtoo comes with an OpenStack diskimage-builder element:
https://github.com/florath/rmtoo/tree/master/contrib/vmsetup
So it should be not that hard to create a complete Debian-VM with rmtoo preinstalled.

Using this setup method a SaaS at AWS Marketplace was created: it should take not more than some minutes to use this predefined VM:
https://aws.amazon.com/marketplace/pp/B077N2PM5B

**Comment by v3ss0n** [comment]
can i build it without latex requirements? I do not need it.
i think this project need to be restructured to be modular.

**Comment by v3ss0n** [comment]
i also suggest you to use Anaconda , that way it is much easier to manage python distro specific problems. It have own virtualenv via conda

**Comment by florath** [comment]
Please don't re-use an already existing issue.

And I kindly ask you to read the documentation before filing issues against rmtoo.
(e.g. Dependencies to external programs)

If you want to make a suggestions or patches (like using anaconda or similar) please fork and submit a merge request.
