### ISSUE TITLE
Nested Topics

### ISSUE THREAD

**Issue by CogPy** [florath/rmtoo#6]
When nesting more than 2 levels deep, the topic's text is suddenly at the end of the section.

**Comment by florath** [comment]
Can you please provide some more information?
Which output module do you use (html, pdf, ...)? Is it only for one or for all?
Is 'topic's text' the description in the topic?

**Comment by CogPy** [comment]
The following ```reqtopics.tex``` output is heavily sanitized for obivous reasons:

    % Output topic 'SwWifi'
    \subsection{WLAN}
    % REQ 'SW30'
    \subsubsection{WiFi}\label{SW30}
    \textbf{Description:} WiFi  Interface  
    
    \textbf{Depends on:} \ref{SW01} \nameref{SW01}
    
    \textbf{Solved by:} \ref{SW31} \nameref{SW31}, \ref{SW32} \nameref{SW32}, \ref{SW33} \nameref{SW33}
    
    % (... more requirements pruned...)
    
    LAN Interface text that belongs before REQ 'SW30'

Unfortunately, I can't create a MWE within reasonable time. If need be, I'll sanitize all requirements files in order to share the issue.

**Comment by florath** [comment]
Hmmm.... This is getting strange:
Can you please have a look at BlackBox Test Case 16?
https://github.com/florath/rmtoo/tree/master/rmtoo/tests/RMTTest-Blackbox/RMTTest-BB016

One topic [1] contains two different text:
```
Name: B0
Text: Some less text.
SubTopic: B1
Text: Some more text.
```

Which are IMHO at the correct position in the output [2]:
Line 3: After the headline
Line 64: After the subtopic

Please note that the topic format is (slightly) different compared to the requirements format: In the topic the order of the tags is important - which is ignored for requirements. The topic should be build in the same order as written in the .tic file (please see: man rmtoo-topic-format)


[1] https://github.com/florath/rmtoo/blob/master/rmtoo/tests/RMTTest-Blackbox/RMTTest-BB016/input/topics/ReqsDocument.tic
[2] https://github.com/florath/rmtoo/blob/master/rmtoo/tests/RMTTest-Blackbox/RMTTest-BB016/result_should/reqtopics.tex

**Comment by CogPy** [comment]
It's a feature, not a bug! RTFM I guess...

> Please note that the topic format is (slightly) different compared to the requirements format: In the topic the order of the tags is important - which is ignored for requirements. The topic should be build in the same order as written in the .tic file (please see: man rmtoo-topic-format)

I've so far only dealt with requirements and ignored the topics.

One positive take-away from this (from rmtoo-topic-format):
> Each topic must be in its own file.  The filename must end in '.tic'.  Only ASCII characters are allowed.  Each line must at maximum 80 characters long.

UTF-8 is supported w/ at least py3.5. Some outputs need to be changed appropriately though.
