### ISSUE TITLE
Broken link in html output of template project

### ISSUE THREAD

**Issue by chrta** [florath/rmtoo#7]
I am running rmtoo in fedora 25 in virtualenv. When i build the template project in contrib/template_project with `make`, the document artifacts/html/ReqsDocument.html contains a broken link:
~~~
<a href="What's all about.html">WhatsAbout</a>
~~~

This should be the other way around. The generated html file for this topic is named WhatsAbout.html

Revision: 01af4aec6e08bb5b44e88257ab0baf840fe55325

**Comment by florath** [comment]
Thanks for the bug report.
Background: instead of the id the name was used in the link.
This will be included in the next release.

**Comment by chrta** [comment]
But shouldn't also be the `What's all about` or `subtopic.get_topic_name()`the text of the link?
